export const LOAD_TODOS = "LOAD_TODOS";
export const LOAD_TODOS_SUCCESS = "LOAD_TODOS_SUCCESS";

export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";

export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";

export const REMOVE_TODO = "REMOVE_TODO";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";

export const SET_LOADING = "SET_LOADING";

export const OPEN_CONFIRM_MODAL = "OPEN_CONFIRM_MODAL";
export const CLOSE_CONFIRM_MODAL = "CLOSE_CONFIRM_MODAL";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const TOGGLE_CREATE_TODO_BAR = "TOGGLE_CREATE_TODO_BAR";
